# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

jobs:
  - job:
    displayName: Agent Job 1    
    steps:
    - script: dotnet restore
      displayName: Restore    
    - script: dotnet build --configuration $(BuildConfiguration)
      displayName: Build    
    - script: dotnet test  --configuration $(BuildConfiguration)
      displayName: Test
    - script: dotnet publish --configuration $(BuildConfiguration) -- output $(build.artifactstagingdirectory)
      displayName: Publish
  
