name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CRED }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false

    - name: Terraform init
      id: init
      run: terraform init        
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}      
      
    - name: Terraform validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform apply
      run: terraform apply -auto-approve

    - name: Publish Api
      run: dotnet publish ./src/ItemTrader.WebAPI/ItemTrader.Api.csproj -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/ItemTrader.Api'

    - name: Publish AuthServer
      run: dotnet publish ./src/ItemTrader.IdentityServer/ItemTrader.IdentityServer.csproj -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/ItemTrader.AuthServer'

    - name: Deploy Api WebAPP
      uses: Azure/Webapps-deploy@v2
      with: 
        app-name: $(terraform output app_service_name_itemtrader_api)
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/ItemTrader.Api
    
    - name: Deploy AuthServer WebApp
      uses: Azure/Webapps-deploy@v2
      with:
        app-name: $(terraform output app_service_name_auth_server)
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/ItemTrader.AuthServer
      
    
